name: Build/Release

on: 
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Tag
      id: tag
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    
    - name: Checkout tag
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.tag.outputs.SOURCE_TAG }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Build
      run: go build -v -o gocopy
