name: Build/Release

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, windows/amd64, darwin/amd64
        goos: [linux, windows]
        goarch: [amd64]
        
    steps:
    - name: Checkout tag
      uses: actions/checkout@v2
      
    - name: Build gocopy
      uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.17"
        overwrite: true
        retry: 10
