name: Build/Release

on: 
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, windows/amd64, darwin/amd64
        goos: [linux, windows, darwin]
        goarch: [amd64]
        
    steps:
    - name: Get Tag
      id: tag
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    
    - name: Checkout tag
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.tag.outputs.SOURCE_TAG }}

    - name: Build gocopy
      uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.17"
        binary_name: "gocopy"
        overwrite: true
        retry: 5
